"""empty message

Revision ID: 2513fa21ca91
Revises: 5bd66bf19efd
Create Date: 2020-04-18 23:01:44.116892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2513fa21ca91'
down_revision = '5bd66bf19efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('server', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_result', schema=None) as batch_op:
        batch_op.drop_column('server')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
