"""empty message

Revision ID: 3c37c2847050
Revises: ec7d9c095804
Create Date: 2020-04-17 18:02:23.209248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c37c2847050'
down_revision = 'ec7d9c095804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_result', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
