"""empty message

Revision ID: 4df45b814015
Revises: 3c37c2847050
Create Date: 2020-04-18 22:39:53.697064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df45b814015'
down_revision = '3c37c2847050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.drop_column('start_timestamp')
        batch_op.drop_column('end_timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_timestamp', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('start_timestamp', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
