"""empty message

Revision ID: 680ddce3f293
Revises: 
Create Date: 2020-04-15 16:06:27.518600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680ddce3f293'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(), nullable=False),
    sa.Column('end_timestamp', sa.DateTime(), nullable=False),
    sa.Column('called_url', sa.String(length=256), nullable=True),
    sa.Column('request', sa.String(length=512), nullable=True),
    sa.Column('response', sa.CLOB(), nullable=True),
    sa.Column('schema', sa.String(length=8), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_result')
    op.drop_table('call')
    # ### end Alembic commands ###
