"""empty message

Revision ID: cfdf12773f54
Revises: 79ac56ce7c3d
Create Date: 2020-04-19 16:07:59.628101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdf12773f54'
down_revision = '79ac56ce7c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_result', schema=None) as batch_op:
        batch_op.drop_index('ix_call_result_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_result', schema=None) as batch_op:
        batch_op.create_index('ix_call_result_date', ['date'], unique=False)

    # ### end Alembic commands ###
